name: Build fping for ARM64

on:
  workflow_dispatch:  # 手动触发
  push:
    tags:             # 打标签时触发
      - 'v*'          # 匹配所有 v 开头的标签

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          make \
          git \
          file  # 用于文件类型检查
        
    - name: Clone fping repository
      run: |
        git clone https://github.com/schweikert/fping.git
        cd fping
        # 使用稳定版本（可选）
        # git checkout 5.1
        
    - name: Generate build system
      run: |
        cd fping
        ./autogen.sh
        
    - name: Configure for ARM64
      run: |
        cd fping
        ./configure \
          --host=aarch64-linux-gnu \
          --prefix=/usr \
          --enable-ipv4 \
          --enable-ipv6 \
          --with-systemd=no
        
    - name: Build fping
      run: |
        cd fping
        make -j$(nproc)
        
    - name: Verify binary architecture
      run: |
        cd fping
        # 使用 file 命令检查架构
        file src/fping
        # 确认输出中包含 "ARM aarch64"
        file src/fping | grep "ARM aarch64" || (echo "错误: 二进制文件不是 ARM aarch64 架构"; exit 1)
        
    - name: Create package
      run: |
        mkdir -p fping-arm64/usr/bin
        cp fping/src/fping fping-arm64/usr/bin/
        
        # 使用 readelf 获取版本信息
        aarch64-linux-gnu-readelf -p .comment fping/src/fping > version_info.txt
        
        # 创建安装脚本
        cat > fping-arm64/install.sh << 'EOF'
        #!/bin/bash
        # fping ARM64 安装脚本
        set -e
        
        # 检查架构
        if [ "$(uname -m)" != "aarch64" ]; then
          echo "警告: 此二进制是为 ARM64 架构编译的"
          echo "当前架构: $(uname -m)"
          read -p "是否继续安装? (y/N) " -n 1 -r
          echo
          if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
          fi
        fi
        
        # 安装 fping
        echo "安装 fping 到 /usr/local/bin"
        sudo install -m 0755 usr/bin/fping /usr/local/bin/fping
        
        # 设置权限
        echo "设置网络权限"
        sudo setcap cap_net_raw+ep /usr/local/bin/fping
        
        echo ""
        echo "=============================================="
        echo "fping 安装成功!"
        echo "版本信息:"
        /usr/local/bin/fping -v 2>&1 || echo "无法获取版本，请在 ARM64 设备上运行"
        echo ""
        echo "使用示例:"
        echo "  fping google.com github.com"
        echo "=============================================="
        EOF
        
        chmod +x fping-arm64/install.sh
        
        # 添加版本信息
        echo "fping ARM64 构建" > fping-arm64/README
        echo "构建日期: $(date)" >> fping-arm64/README
        echo "来源: https://github.com/schweikert/fping" >> fping-arm64/README
        cat version_info.txt >> fping-arm64/README
        
        # 打包
        tar czf fping-arm64.tar.gz -C fping-arm64 .
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fping-arm64
        path: fping-arm64.tar.gz
        retention-days: 7
